runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /Style
  static_dir: style

- url: /Style
  static_dir: recipesStyle

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
